// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	zap2 "github.com/angelokurtis/go-laboratory/internal/zap"
	"github.com/angelokurtis/go-laboratory/internal/zapr"
	"github.com/go-logr/logr"
	"go.uber.org/zap"
)

// Injectors from injectors.go:

func ZapLogger() (*zap.Logger, error) {
	encoderConfig := zap2.NewEncoderConfig()
	config := zap2.NewConfig(encoderConfig)
	logger, err := zap2.NewLogger(config)
	if err != nil {
		return nil, err
	}
	return logger, nil
}

func LogrLogger() (logr.Logger, error) {
	encoderConfig := zap2.NewEncoderConfig()
	config := zap2.NewConfig(encoderConfig)
	logger, err := zap2.NewLogger(config)
	if err != nil {
		return logr.Logger{}, err
	}
	logrLogger := zapr.NewLogger(logger)
	return logrLogger, nil
}
