// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initialize() (*Service, error) {
	currentDirectory, err := NewCurrentDirectory()
	if err != nil {
		return nil, err
	}

	db, err := NewBoltDB(currentDirectory)
	if err != nil {
		return nil, err
	}

	service := &Service{
		BoltDB: db,
	}

	return service, nil
}
