// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	zap2 "github.com/angelokurtis/go-laboratory/internal/zap"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewLogger() (*zap.Logger, error) {
	logger, err := zap2.NewLogger()
	if err != nil {
		return nil, err
	}
	return logger, nil
}
