version: '3.8'

services:
  mysql:
    container_name: "mysql"
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "<password>"
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.103.0.1/16