// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/angelokurtis/go-laboratory/internal/zap"
	"github.com/angelokurtis/go-laboratory/internal/zapr"
	"github.com/go-logr/logr"
)

// Injectors from wire.go:

func NewLogger() (logr.Logger, error) {
	encoderConfig := zap.NewEncoderConfig()
	config := zap.NewConfig(encoderConfig)
	logger, err := zap.NewLogger(config)
	if err != nil {
		return logr.Logger{}, err
	}
	logrLogger := zapr.NewLogger(logger)
	return logrLogger, nil
}
